jekyll:
  image: jekyll/jekyll:3.8
  command: sh -c 'gem install jekyll bundler; bundler; bundle exec jekyll serve -b "" --host 0.0.0.0 --livereload'
  ports:
    - 4000:4000
  volumes:
    - .:/srv/jekyll
